# Generated by Django 3.2.4 on 2021-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_auto_20210702_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone'), ('Car', 'Car'), ('Record', 'Record')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone'), ('Car', 'Car'), ('Record', 'Record')], max_length=50, null=True),
        ),
    ]
